name: Test
on:
  push:
    branches:
      - main
      - master
      - next

env:
  RUST_BACKTRACE: 1

jobs:
    echo:
        name: Echo
        runs-on: ubuntu-latest

        steps:
          - run: echo "🎉 The job was automatically triggered on repo ${{ github.repository }}."
